const main = require('../index.js')
// await page.goto('https://geoinstrum.quickbase.com/db/bjfbwcch8?a=er&r=izh&rl=cmp')
// await page.setViewport({ width: 2133, height: 1052 })

export async function newItem(browser, page) {
    await page.waitForSelector('.formRow > #tdf_6 > .cell > nobr > .Vibrant')
    await page.click('.formRow > #tdf_6 > .cell > nobr > .Vibrant')
    await navigationPromise
    await page.waitForSelector('.css-1qp07gu > .Select > .Select-control > #react-select-2--value > .Select-placeholder')
    await page.click('.css-1qp07gu > .Select > .Select-control > #react-select-2--value > .Select-placeholder')
    await page.waitForSelector('.css-1qp07gu > .Select > .Select-control > #react-select-9--value > .Select-placeholder')
    await page.click('.css-1qp07gu > .Select > .Select-control > #react-select-9--value > .Select-placeholder')
    await page.waitForSelector('.css-1qp07gu > .Select > .Select-control > #react-select-10--value > .Select-placeholder')
    await page.click('.css-1qp07gu > .Select > .Select-control > #react-select-10--value > .Select-placeholder')
    await page.waitForSelector('div > #sect_s6 #tdl_5')
    await page.click('div > #sect_s6 #tdl_5')
    await page.waitForSelector('.css-1qp07gu > .Select > .Select-control > #react-select-11--value > .Select-placeholder')
    await page.click('.css-1qp07gu > .Select > .Select-control > #react-select-11--value > .Select-placeholder')
    await page.waitForSelector('.Select > .Select-control > #react-select-9--value > .Select-input > input')
    await page.click('.Select > .Select-control > #react-select-9--value > .Select-input > input')
    await page.waitForSelector('.Select > .Select-control > #react-select-9--value > .Select-input > input')
    await page.click('.Select > .Select-control > #react-select-9--value > .Select-input > input')
    await page.waitForSelector('.css-1qp07gu > .Select > .Select-control > #react-select-11--value > .Select-placeholder')
    await page.click('.css-1qp07gu > .Select > .Select-control > #react-select-11--value > .Select-placeholder')
    await page.waitForSelector('div > #sect_s6 #tdl_6')
    await page.click('div > #sect_s6 #tdl_6')
    await page.waitForSelector('tbody #\_fid_29')
    await page.click('tbody #\_fid_29')
    await page.waitForSelector('tbody #\_fid_10')
    await page.click('tbody #\_fid_10')
    await page.waitForSelector('#dbFormContainer > #formContentsContainer > #formContents > .sectionDiv:nth-child(4) > .Divider')
    await page.click('#dbFormContainer > #formContentsContainer > #formContents > .sectionDiv:nth-child(4) > .Divider')
    await page.waitForSelector('div > #sect_s1 #tdl_13')
    await page.click('div > #sect_s1 #tdl_13')
    await page.waitForSelector('div > #sect_s1 #tdl_13')
    await page.click('div > #sect_s1 #tdl_13')
    await page.waitForSelector('tbody #\_fid_9')
    await page.click('tbody #\_fid_9')
    await page.waitForSelector('#interiorContainer > #dbFormContainer > #formContentsContainer #footerSaveButton')
    await page.click('#interiorContainer > #dbFormContainer > #formContentsContainer #footerSaveButton')
    await navigationPromise
    await page.waitForSelector('.gridOuterTable > tbody > tr > .gridEmbCell > .gridEmbDiv')
    await page.click('.gridOuterTable > tbody > tr > .gridEmbCell > .gridEmbDiv')
    await page.waitForSelector('.gridOuterTable > tbody > tr > .gridEmbCell > .gridEmbDiv')
    await page.click('.gridOuterTable > tbody > tr > .gridEmbCell > .gridEmbDiv')
    await page.waitForSelector('tr #mainTE')
    await page.click('tr #mainTE')
    await page.waitForSelector('.gridOuterTable > tbody > tr > .gridEmbCell > .gridEmbDiv')
    await page.click('.gridOuterTable > tbody > tr > .gridEmbCell > .gridEmbDiv')
    await page.waitForSelector('.gridOuterTable > tbody > tr > .gridEmbCell > .gridEmbDiv')
    await page.click('.gridOuterTable > tbody > tr > .gridEmbCell > .gridEmbDiv')
    await page.waitForSelector('.gridOuterTable > tbody > tr > .gridEmbCell > .gridEmbDiv')
    await page.click('.gridOuterTable > tbody > tr > .gridEmbCell > .gridEmbDiv')
    await page.waitForSelector('.gridOuterTable > tbody > tr > .gridEmbCell > .gridEmbDiv')
    await page.click('.gridOuterTable > tbody > tr > .gridEmbCell > .gridEmbDiv')
    await page.waitForSelector('#sect_s2 > tbody > .formRow > #tdf_6 > .cell')
    await page.click('#sect_s2 > tbody > .formRow > #tdf_6 > .cell')
    await page.waitForSelector('.formRow > #tdf_6 > .cell > nobr > .Vibrant')
    await page.click('.formRow > #tdf_6 > .cell > nobr > .Vibrant')
    await navigationPromise
}

await newItem(browser, page)
